/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteRouteImport } from './routes/updates/route'
import { Route as FieldsRouteRouteImport } from './routes/fields/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FieldsFieldIdRouteRouteImport } from './routes/fields/$fieldId/route'
import { Route as AuthSignupRouteRouteImport } from './routes/auth/signup/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'

const UpdatesRouteRoute = UpdatesRouteRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRouteRoute = FieldsRouteRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsFieldIdRouteRoute = FieldsFieldIdRouteRouteImport.update({
  id: '/$fieldId',
  path: '/$fieldId',
  getParentRoute: () => FieldsRouteRoute,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/fields': typeof FieldsRouteRouteWithChildren
  '/updates': typeof UpdatesRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/fields/$fieldId': typeof FieldsFieldIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/fields': typeof FieldsRouteRouteWithChildren
  '/updates': typeof UpdatesRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/fields/$fieldId': typeof FieldsFieldIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/fields': typeof FieldsRouteRouteWithChildren
  '/updates': typeof UpdatesRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/fields/$fieldId': typeof FieldsFieldIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fields'
    | '/updates'
    | '/auth/login'
    | '/auth/signup'
    | '/fields/$fieldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fields'
    | '/updates'
    | '/auth/login'
    | '/auth/signup'
    | '/fields/$fieldId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/fields'
    | '/updates'
    | '/auth/login'
    | '/auth/signup'
    | '/fields/$fieldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  FieldsRouteRoute: typeof FieldsRouteRouteWithChildren
  UpdatesRouteRoute: typeof UpdatesRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields/$fieldId': {
      id: '/fields/$fieldId'
      path: '/$fieldId'
      fullPath: '/fields/$fieldId'
      preLoaderRoute: typeof FieldsFieldIdRouteRouteImport
      parentRoute: typeof FieldsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthSignupRouteRoute: typeof AuthSignupRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthSignupRouteRoute: AuthSignupRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface FieldsRouteRouteChildren {
  FieldsFieldIdRouteRoute: typeof FieldsFieldIdRouteRoute
}

const FieldsRouteRouteChildren: FieldsRouteRouteChildren = {
  FieldsFieldIdRouteRoute: FieldsFieldIdRouteRoute,
}

const FieldsRouteRouteWithChildren = FieldsRouteRoute._addFileChildren(
  FieldsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  FieldsRouteRoute: FieldsRouteRouteWithChildren,
  UpdatesRouteRoute: UpdatesRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
